default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_app_development
test:
  <<: *default
  database: photo_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
